### ISSUE TITLE
[Documentation] Update website name 

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#1]

**Comment by Shivashish-rwt** [comment]
Hey can i contribute??

**Comment by shivansh12032004** [comment]
Hey, can you assign me this issue?

**Comment by Sanket1308** [comment]
@Shivashish-rwt @shivansh12032004 Suggest names here in discussion! Will assign accordingly.

**Comment by Shivashish-rwt** [comment]
@Sanket1308 
How about:
1. Quolingo
2. Quogenic
3. Quotemator

**Comment by shivansh12032004** [comment]
@Sanket1308 
Here are my suggestions-
1. Quoter
2. QuoteBuzz
3. Iquote
4. QuoteMaker
5. Quoteable

**Comment by Sanket1308** [comment]
@shivansh12032004 Go ahead with QuoteBuzz. 🚀

**Comment by Sanket1308** [comment]
@Shivashish-rwt Good suggestions. For now please contribute to other issues.
Check other issues here: 
- https://github.com/Sanket1308/Weather-App/issues
- https://github.com/Sanket1308/javascript-quote-generator/issues
