### ISSUE TITLE
[HTML] Add 'Tweet this' text beside the Twitter button.

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#15]
![Screenshot (1092)](https://user-images.githubusercontent.com/79108273/193445963-2e2b4cbd-844c-4fa1-a9d7-eec5a922cf5e.png)

**Comment by KaifKhan7393** [comment]
You want to remove the twitter icon and add the text

**Comment by Rahul-Palahwat** [comment]
We can keep the twitter icon but on hovering we can show Tweet this , is this you wanna get implemented?
@Sanket1308 could you please assign this issue to me

**Comment by Sanket1308** [comment]
Just add the text. Contribute well🚀

**Comment by Sanket1308** [comment]
Yeah! Hover effect will be great. Go for it, @Rahul-Palahwat!

**Comment by NayanDeshmukh2001** [comment]
already working on it assign it to me if open

**Comment by Sanket1308** [comment]
Hey NayanDeshmukh,
This one is assigned already. Find more issues here:
https://github.com/Sanket1308/Weather-App/
https://github.com/Sanket1308/javascript-quote-generator

**Comment by KaifKhan7393** [comment]
This issue is already completed by Rahul so what other thing I do about this issue?
