### ISSUE TITLE
[CSS] Add hover effect to buttons

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#18]
[CSS] Add hover effect to Tweet this and New quote buttons to change color on hover

Tweet button details:
- Before hover: Twitter icon + Tweet this text + Black and white color
- After hower: Twitter icon + Tweet this text + Black and blue color

Next quote button details:
- Before hover: Next icon + Next Quote text + Black and white color
- After hower: Next icon + Next Quote text + Black and blue color

**Comment by bloodmonk7** [comment]
I can do this if I am allowed to help in multiple roles

**Comment by harshk-codes** [comment]
@Sanket1308 i've made a PR where i've changed icon to Tweet this and has a hovering effect( changes background color of button to twitter blue color and text to original #333 black color

**Comment by shivansh12032004** [comment]
@Sanket1308 can I help with this? Thanks in advance

**Comment by Rahul-Palahwat** [comment]
Hey @Sanket1308 can i work on it?

**Comment by Skysparko** [comment]
@Sanket1308 hey can i work on it?

**Comment by Sanket1308** [comment]
Go ahead. Contribute well! @Skysparko @Rahul-Palahwat

**Comment by Skysparko** [comment]
@Sanket1308 done.

**Comment by Zackaria-Slimane** [comment]
would love to give this a try , let me know if i can help :)

**Comment by Sanket1308** [comment]
Completed!
