### ISSUE TITLE
{Documentation] Update README.md

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#2]
Must include
- Screenshots
- Badges
- Color references
- Live Project link
- Contributing.md link
- Code-of-conduct.md
- Deployment information
- Etc

**Comment by singhkaran202** [comment]
Hey @Sanket1308, I'd love to work on this if that's OK.

**Comment by Sanket1308** [comment]
Go ahead, @singhkaran202 
Contribute well!🚀

**Comment by singhkaran202** [comment]
It would be motivating for me @Sanket1308!! if you can assign me the issue

**Comment by singhkaran202** [comment]
Hey @Sanket1308, Should I delete the demo contents( like the screenshot of demo and link of demo javascript quote generator) and replace them with that of live projects’ .................or should I only just add(live project’s stuff) and no deletion of old content(demo content) in Readme?

**Comment by singhkaran202** [comment]
Hey @Sanket1308, Should I delete the demo contents( like the screenshot of demo and link of demo javascript quote generator) and replace them with that of live projects’ .................or should I only just add(live project’s stuff) and no deletion of old content(demo content) in Readme?

**Comment by Sanket1308** [comment]
Add latest content!

**Comment by singhkaran202** [comment]
@Sanket1308, Could you please tell me that what you actually meant by "color references" in your above-mentioned issue comment?
