### ISSUE TITLE
[HTML] Add favicon

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#3]
Add favicon to site

**Comment by najeebkp** [comment]
Hi @Sanket1308 , can you please assign me this?

**Comment by vishalpatil20** [comment]
Hey @Sanket1308  I would love to contribute

**Comment by Sanket1308** [comment]
@najeebkp @vishalpatil20 Share favicon design here in discussion. One with the better design will be assigned to go ahead with the PR🚀

**Comment by trishitchar** [comment]
Hey, I would like to work on this. Thanks!

**Comment by Sanket1308** [comment]
@najeebkp @vishalpatil20 @trishitchar Share favicon design here in discussion within next 6 hours. One with the better design will be assigned to go ahead with the PR🚀

**Comment by najeebkp** [comment]
@trishitchar can go ahead. I'm opting out! Thanks!

**Comment by 9389lalit** [comment]
Hey,,I would like to work  on this

**Comment by vishalpatil20** [comment]
![Adobe_Express_20221002_1057120_1](https://user-images.githubusercontent.com/97267034/193439424-226a73b9-2d65-4f0d-a506-399a6233fe0d.png)
@Sanket1308 check this out. 
Also I didn't get any name for website so I thought of quote generator
If you have any name then I will make required changes.

**Comment by vishalpatil20** [comment]
> ![Adobe_Express_20221002_1057120_1](https://user-images.githubusercontent.com/97267034/193439424-226a73b9-2d65-4f0d-a506-399a6233fe0d.png) @Sanket1308 check this out. Also I didn't get any name for website so I thought of quote generator If you have any name then I will make required changes.

Its just the design I will later make the favicon after approval

**Comment by Sanket1308** [comment]
- Remove name; Just keep the quotes sign and centre them
- Use white color in background
- Start working on PR🚀

**Comment by Sanket1308** [comment]
@9389lalit Share your design!

**Comment by sachin2709** [comment]
can i share my design @Sanket1308

**Comment by Sanket1308** [comment]
Yes, @sachin2709!

**Comment by sachin2709** [comment]
![Quotes Generator-1 (1)](https://user-images.githubusercontent.com/96466673/193440800-94c5163c-28b5-4413-81be-fd2fe760b5ea.png)
![Quotes Generator-1](https://user-images.githubusercontent.com/96466673/193440804-9efeb554-1714-459f-b81c-1cefdc2a0f59.png)

check it sir @Sanket1308

**Comment by Sanket1308** [comment]
@sachin2709 Could be better! Work on different issues for now.
Check more issues here: 
- https://github.com/Sanket1308/Weather-App/issues
- https://github.com/Sanket1308/javascript-quote-generator/issues

**Comment by Sanket1308** [comment]
Completed!
