### ISSUE TITLE
[Fix] Image doesnt load on first quote

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#33]
![Screenshot (1098)](https://user-images.githubusercontent.com/79108273/193464915-e4115028-aea1-4eea-9bda-ea18f6559283.png)

**Comment by yesimhozman** [comment]
can you assign it to me?

**Comment by saroshfarhan** [comment]
@yesimhozman I think this might be because of a wrong path to BG in style.css.

**Comment by yesimhozman** [comment]
Thank you for your explanation @saroshfarhan . I was thinking the same thing. Happy HacktoberFest!!

**Comment by Sanket1308** [comment]
True spirt of open-source shown over there🚀 
Keep up the good work @saroshfarhan!

**Comment by ofaltins** [comment]
Sorry - i jumped the gun and added a PR - didn't notice that the issue was already assigned 🙏
