### ISSUE TITLE
Create website responsive

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#35]

**Comment by Skysparko** [comment]
hey, @Sanket1308  can I work on it?

**Comment by Aragorn-64** [comment]
Hi @Sanket1308 Could i try this?

**Comment by Sanket1308** [comment]
@Skysparko @Aragorn-64 
Go ahead! Contribute well🚀

**Comment by Aragorn-64** [comment]
@Sanket1308 Can I use bootstrap?
