### ISSUE TITLE
Add 'Tweet this' text beside the Twitter button.

### ISSUE THREAD

**Issue by bloodmonk7** [Sanket1308/javascript-quote-generator#4]

**Comment by Sanket1308** [comment]
That's a great feature! 🚀 Share your approach in detail. You will take the user's twitter handle on input?

**Comment by bloodmonk7** [comment]
No, what we can do is just by using twitter api, when a user taps on the tweet button we will redirect them to their twitter client and that will open the tweet option and pre-write the quote with author's name(if there) and they just have to tap on tweet button.

**Comment by Sanket1308** [comment]
Great approach! Go ahead, @bloodmonk7 !

**Comment by Sanket1308** [comment]
Add 'Tweet this' text beside the Twitter button.
