### ISSUE TITLE
[HTML] Add appropriate image/image slider in background

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#5]
- Ask to be assigned on this issue.
- Share your approach/ image here before writing code.
- Write good documented commits/PR
- All the best!🚀

**Comment by bloodmonk7** [comment]
Can i do this?

**Comment by amanrk28** [comment]
I'd like to take this up

**Comment by Sanket1308** [comment]
@bloodmonk7 @amanrk28 
Share your approach: 
Will you add a static image or a image slider? It will be great if you can implement image slider. Image should changes with each changing quote.

Also share your image(s) here before writing code. Once done with these I will assign it to you!

**Comment by amanrk28** [comment]
> @bloodmonk7 @amanrk28 Share your approach: Will you add a static image or a image slider? It will be great if you can implement image slider. Image should changes with each changing quote.
> 
> Also share your image(s) here before writing code. Once done with these I will assign it to you!

I will be adding an image slider. More like a fader which changes to a random image everytime you click to get a new quote with a smooth transition. Also the image will be a little blurred so it doesn't take the focus away from the quote box. This is one of the images which I've clicked. I have more somewhere on my laptop, have to search through them which will be similar to this one.
![bg](https://user-images.githubusercontent.com/62303924/193438682-a1ec0dee-6bbd-4c74-982e-0a9f760550ba.jpg)

**Comment by 9389lalit** [comment]
[background](https://in.pinterest.com/pin/152559506114560854/)
I would love to work on it

**Comment by sachin2709** [comment]
I Want To Work On This Task,Please assign It to me @Sanket1308

**Comment by Sanket1308** [comment]
@amanrk28  Good elaboration there. Go for it! 🚀

**Comment by amanrk28** [comment]
Created a PR #13

**Comment by saroshfarhan** [comment]
@Sanket1308 how about we chose a word from the quote itself and search images related to it on Unsplash and fetch the image making an API call so now we have an image relating to the quote itself, maybe we can tweak our quotes object to contain a central idea word which can make the Unsplash API call easier. 

Our object will look like:

`const quotes = [
    {
      quote:
        '"Some fail to bear in mind that everyone is sentenced to death. Death is a treacherous virus that strikes randomly. The only truth is that nobody is going to make it out alive. We are all living on probation and our expiry date is indefinite. "',
      person: 'Erik Pevernagie',
      keyword: 'death'
    }
]
`

**Comment by Sanket1308** [comment]
Nice idea, @saroshfarhan ! Go for it. Assigning you on it.🚀

**Comment by Sanket1308** [comment]
Completed!
