### ISSUE TITLE
[Documentation] Add more quotes in script.js

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#6]
- Add appropriate quotes.
- Follow proper syntax.
- Write Author's name correctly.
- Make PR.🚀

**Comment by Fortezza15** [comment]
assign me this issue!

**Comment by bloodmonk7** [comment]
I can do this if you want... Assign it to me if you think twitter button doesn't go well

**Comment by Sanket1308** [comment]
Assigned! Contribute well, @Fortezza15 🚀

**Comment by Anchit1909** [comment]
Hey Sanket,
I have an already existing database of quotes. The quantity is more than 150.
Assign me this issue so I can start working on it.

**Comment by Sanket1308** [comment]
Great! Go ahead🚀

**Comment by Shamik1836** [comment]
I have a huge collection of quotes that I can contribute, can you please assign this to me?

**Comment by Sanket1308** [comment]
Go for it! contribute well. 🚀

**Comment by akshaykhoje** [comment]
Please assign this issue to me.

**Comment by shivansh12032004** [comment]
Hey, can I work on this issue as well?

**Comment by saroshfarhan** [comment]
@Sanket1308 Can I also add some quotes?

**Comment by Zackaria-Slimane** [comment]
I would love to add some too if you're still looking for more , add me to assignes and i'll get to it :)

**Comment by Sanket1308** [comment]
@Zackaria-Slimane 
Go ahead! Contribute well🚀
