### ISSUE TITLE
[Enhancement] Improve UI

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/javascript-quote-generator#9]
- Explore your creativity.
- Share screenshots in PR discussion
- Discuss your approach while asking for getting assigned.
- All the best🚀

**Comment by Misterr-H** [comment]
are we free to use tailwindcss? @Sanket1308

**Comment by Sanket1308** [comment]
Yes, sure!

**Comment by Misterr-H** [comment]
@Sanket1308 
okay, please Assign.
will apply hover effects, change colors, improve fonts and will see what can I do more to improve

**Comment by Sanket1308** [comment]
Good! Have assigned you. Contribute well🚀

**Comment by saroshfarhan** [comment]
@Misterr-H Do you have some mock designs in hand? We can pass around some mock UI designs (maybe hi-fidelity wireframes) here and you can go ahead and develop it, what say?

**Comment by Zackaria-Slimane** [comment]
> @Misterr-H Do you have some mock designs in hand? We can pass around some mock UI designs (maybe hi-fidelity wireframes) here and you can go ahead and develop it, what say?

I would love to get a shot at developing some of the designs you have ! let me know what you have availlable

**Comment by Misterr-H** [comment]
hello @saroshfarhan 
Sorry, i just checked in
Yeah, thats great idea

**Comment by Misterr-H** [comment]
@saroshfarhan Pass some designs

**Comment by saroshfarhan** [comment]
Hi @Misterr-H @Zackaria-Slimane @Sanket1308 made a Figma design for the desktop browser.
Feel free to comment and suggest changes. Did some changes to remove clutter and drive CTA to generate a new quote. The tweet this button is removed and only appears when one hovers over the quote text (generally people will try to copy the quote so the assumption is the user will hover or at least take the mouse pointer to the text and this will open up the option to tweet the text).

Landing Page
<img width="692" alt="Landing page" src="https://user-images.githubusercontent.com/12766730/193464085-be29ad0f-9c21-4a03-b59f-1327ac7f5042.png">

Hover Effect on text
<img width="684" alt="On hover effect to tweet" src="https://user-images.githubusercontent.com/12766730/193464127-3b972fc9-351c-4450-9c73-4c5cfeb00f4b.png">

**Comment by Sanket1308** [comment]
Awesome work, @saroshfarhan 🚀
Seems perfect to me! Just in place of 'Generate', there should be 'Next quote'

**Comment by saroshfarhan** [comment]
@Sanket1308  will do, also need to add the name of the website, this was just a mock up, will polish it up (alignments and font sizes and also need to add mobile and iPad mockup to be responsive.)and add the Figma link in README.md. Also, request you to create and issue for adding responsiveness to the site.

**Comment by Misterr-H** [comment]
vvv nice @saroshfarhan . appreciate design

**Comment by Sanket1308** [comment]
#35 Done, @saroshfarhan!

**Comment by Misterr-H** [comment]
hey @saroshfarhan , tell me the name of the font used please

**Comment by Misterr-H** [comment]
thanks in advance

**Comment by saroshfarhan** [comment]
@Misterr-H I used Gilda Display. Idk if it is open-source or not, let me check one from google fonts for an alternate open-source font. Will add it in the design file.

**Comment by Misterr-H** [comment]
okay @saroshfarhan

**Comment by saroshfarhan** [comment]
@Misterr-H Gilda Display is open source and from [google fonts](https://fonts.google.com/specimen/Gilda+Display)

**Comment by Misterr-H** [comment]
okay @saroshfarhan

**Comment by Misterr-H** [comment]
hello @Sanket1308 
<img width="1440" alt="Screenshot 2022-10-03 at 12 00 08 AM" src="https://user-images.githubusercontent.com/55010619/193470123-572e984b-d490-4b8f-99c0-2f48aa2e8ecf.png">

I hv done my best, please review. Hover to tweet over text will require some additional JS so I've exluded that for now.
I hope u will like it :)
Thankyou

**Comment by Misterr-H** [comment]
Thankyou very much @saroshfarhan

**Comment by saroshfarhan** [comment]
@Sanket1308 @Misterr-H have added Figma link and raised PR https://github.com/Sanket1308/javascript-quote-generator/pull/44
